# Serenity Properties for API Testing
serenity.project.name=Reservas Sofka API Automation
serenity.logging=VERBOSE

# Base URL for APIs
restapi.baseurl=http://localhost:3004
restapi.authurl=http://localhost:3001

# Output directory for reports
serenity.outputDirectory=target/site/serenity
